export const KEY = {
    author: "author",
    connect: "connect",
    date: "date",
    description: "description",
    downloadURL: "downloadURL",
    exclude: "exclude",
    grant: "grant",
    homepageURL: "homepageURL",
    icon: "icon",
    include: "include",
    inject_into: "inject-into",
    license: "license",
    match: "match",
    name: "name",
    namespace: "namespace",
    noframes: "noframes",
    require: "require",
    resource: "resource",
    run_at: "run-at",
    updateURL: "updateURL",
    version: "version",
};
