name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [current, lts/*, lts/-1, lts/-2]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Test
        run: |
          npm test
      - name: Build
        run: |
          npm run build
        env:
          CI: true
      - name: Pack
        id: pack
        run: |
          echo "::set-output name=tarball::$(pwd)/$(npm pack)"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: ${{ matrix.node-version == 'lts/*' }}
        with:
          name: package-tarball
          path: ${{ steps.pack.outputs.tarball }}
  userscripts:
    name: Dependent Userscripts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
          - SimonAlling/better-sweclockers
          - SimonAlling/example-userscript
        node-version: [current, lts/*, lts/-1, lts/-2]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clone userscript
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repository }}
          path: dependent-userscripts/${{ matrix.repository }} # Must be relative to github.workspace, apparently.
      - name: Move userscript
        run: |
          mkdir -p "${TARGET_DIR}"
          mv --no-target-directory "${{ github.workspace }}/dependent-userscripts/${{ matrix.repository }}" "${TARGET_DIR}"
        env:
          TARGET_DIR: ${{ runner.temp }}/${{ matrix.repository }}
      - name: Install userscript dependencies
        working-directory: ${{ runner.temp }}/${{ matrix.repository }}
        run: |
          npm ci
      - name: Download artifact
        uses: actions/download-artifact@v3
        id: download
        with:
          name: package-tarball
      - name: Install userscript-metadata
        working-directory: ${{ runner.temp }}/${{ matrix.repository }}
        run: |
          npm install "${{ steps.download.outputs.download-path }}/userscript-metadata-*.tgz"
      - name: Build userscript
        working-directory: ${{ runner.temp }}/${{ matrix.repository }}
        run: |
          npm run build
